import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import Announcement_banner from "@/components/layout/announcement_banner";
import React from "react";
import AnnouncementBannerComponent from "@/components/layout/announcement_banner";
import TheHeader from "@/components/layout/TheHeader";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <main className={'relative'}>
            <AnnouncementBannerComponent/>
            <TheHeader/>
            {children}
        </main>
        </body>
        </html>
    );
}
